version: '3'
services: 
  database:
    image: mongo:5
    container_name: mongodb
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./data:/data/db
    ports:
      - '27017-27019:27017-27019'